package corrosion

import (
	"context"
	"testing"
)

func TestInsertAndListSnapshots(t *testing.T) {
	c := testClient(t)
	ctx := context.Background()

	// Insert a VM first (snapshots have a FK-like relationship)
	c.Execute(ctx, `INSERT INTO vms (name, stack_name, host_name, spec, state, cpu_actual, mem_actual, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		"vm1", "", "node1", "{}", "running", 2, 1024, "2024-01-01T00:00:00Z", "2024-01-01T00:00:00Z")

	snap := SnapshotRecord{
		VMName:   "vm1",
		HostName: "node1",
		Name:     "snap-1",
		State:    "ok",
	}
	if err := InsertSnapshot(ctx, c, snap); err != nil {
		t.Fatalf("InsertSnapshot: %v", err)
	}

	snaps, err := ListSnapshots(ctx, c, "vm1")
	if err != nil {
		t.Fatalf("ListSnapshots: %v", err)
	}
	if len(snaps) != 1 {
		t.Fatalf("expected 1 snapshot, got %d", len(snaps))
	}
	if snaps[0].Name != "snap-1" {
		t.Errorf("Name = %q, want snap-1", snaps[0].Name)
	}
	if snaps[0].VMName != "vm1" {
		t.Errorf("VMName = %q, want vm1", snaps[0].VMName)
	}
	if snaps[0].HostName != "node1" {
		t.Errorf("HostName = %q, want node1", snaps[0].HostName)
	}
	if snaps[0].ID == "" {
		t.Error("ID should be auto-generated")
	}
}

func TestListSnapshots_Empty(t *testing.T) {
	c := testClient(t)
	snaps, err := ListSnapshots(context.Background(), c, "nonexistent")
	if err != nil {
		t.Fatalf("ListSnapshots: %v", err)
	}
	if len(snaps) != 0 {
		t.Errorf("expected 0 snapshots, got %d", len(snaps))
	}
}

func TestDeleteSnapshot(t *testing.T) {
	c := testClient(t)
	ctx := context.Background()

	c.Execute(ctx, `INSERT INTO vms (name, stack_name, host_name, spec, state, cpu_actual, mem_actual, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		"vm1", "", "node1", "{}", "running", 2, 1024, "2024-01-01T00:00:00Z", "2024-01-01T00:00:00Z")

	InsertSnapshot(ctx, c, SnapshotRecord{VMName: "vm1", HostName: "node1", Name: "snap-a", State: "ok"})
	InsertSnapshot(ctx, c, SnapshotRecord{VMName: "vm1", HostName: "node1", Name: "snap-b", State: "ok"})

	if err := DeleteSnapshot(ctx, c, "vm1", "snap-a"); err != nil {
		t.Fatalf("DeleteSnapshot: %v", err)
	}

	snaps, _ := ListSnapshots(ctx, c, "vm1")
	if len(snaps) != 1 {
		t.Fatalf("expected 1 snapshot after delete, got %d", len(snaps))
	}
	if snaps[0].Name != "snap-b" {
		t.Errorf("remaining snapshot = %q, want snap-b", snaps[0].Name)
	}
}

func TestInsertSnapshot_IDAutoGenerated(t *testing.T) {
	c := testClient(t)
	ctx := context.Background()

	c.Execute(ctx, `INSERT INTO vms (name, stack_name, host_name, spec, state, cpu_actual, mem_actual, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		"vm1", "", "node1", "{}", "running", 2, 1024, "2024-01-01T00:00:00Z", "2024-01-01T00:00:00Z")

	InsertSnapshot(ctx, c, SnapshotRecord{VMName: "vm1", HostName: "node1", Name: "snap-1", State: "ok"})
	InsertSnapshot(ctx, c, SnapshotRecord{VMName: "vm1", HostName: "node1", Name: "snap-2", State: "ok"})

	snaps, _ := ListSnapshots(ctx, c, "vm1")
	if len(snaps) != 2 {
		t.Fatalf("expected 2 snapshots, got %d", len(snaps))
	}
	if snaps[0].ID == snaps[1].ID {
		t.Errorf("snapshot IDs should be unique, both are %q", snaps[0].ID)
	}
}
