package corrosion

// appendOnlyTables are immutable append-only tables: a replicated INSERT is applied with
// INSERT OR IGNORE and never LWW-gated, because a row never changes after creation.
var appendOnlyTables = map[string]bool{
	"fencing_log":  true,
	"audit_log":    true,
	"mutation_log": true,
	"vm_events":    true,
}

// deriveDisposition classifies a parsed replicated statement into the disposition the apply
// path uses. It is the single source of truth for authorization: the compatibility ledger
// (stmtledger_generated.go) is generated by running it over every builder statement, so a
// fingerprint's ledger disposition and its derivation can never disagree. A statement it
// can't classify safely returns an error, which fails the CI guard (the shape must be made
// classifiable before it can ship).
func deriveDisposition(sh StmtShape) (Disposition, ConcurrencyCategory, error) {
	t := sh.Table
	// Custom-merge tables (monotone lifecycle / immutable journal) merge by their own rule
	// regardless of statement kind.
	if customMergeTables[t] != nil {
		return DispCustomMerge, CatNone, nil
	}
	switch sh.Kind {
	case KindInsert:
		// append-only applies to INSERTs: never overwrite an existing immutable row.
		if appendOnlyTables[t] {
			return DispAppendOnly, CatNone, nil
		}
		if sh.OnConflict != nil {
			return DispExplicitUpsert, CatNone, nil
		}
		return DispPlainInsert, CatNone, nil
	case KindUpdate:
		if sh.HasFullPKIdentity {
			// A full-PK UPDATE is LWW-gated only when it binds updated_at (the clock the gate
			// compares).
			if sh.UpdatedAtParamIdx >= 0 {
				return DispFullPKUpdate, CatNone, nil
			}
			// A no-clock full-PK UPDATE (no bound updated_at) is NOT auto-derived: applying it
			// verbatim can regress a replicated timestamp when writes from different origins
			// arrive out of order (session/token last_used_at). It requires an EXPLICIT,
			// audited per-fingerprint policy (explicitPolicyDefs) that says whether it is
			// idempotent/terminal (apply verbatim) or a monotone-timestamp update (advance
			// only). LedgerEntryFor consults the explicit policy first; reaching here means a
			// no-clock shape has none, which fails the guard until one is added.
			return "", CatNone, invalidf("no-clock full-PK update on %s requires an explicit ledger policy", sh.Table)
		}
		// A bulk UPDATE (no full-PK identity) is applied by per-row LWW expansion — but only
		// when that is provably safe: it must advance a clock (SET updated_at = ?) so each
		// matched row can be LWW-gated, and it must NOT modify a primary-key column (rekeying
		// a PK can't be gated by that PK; those cascades are row-scoped at the source). Any
		// other bulk shape is unsupported and back-pressures.
		if bulkUpdateIsPerRowLWWSafe(sh) {
			return DispBulkUpdate, CatPerRowLWW, nil
		}
		return DispBulkUpdate, CatUnsupported, nil
	case KindDelete:
		// A DELETE reaches the ledger only when emitted by a known replicating builder, so
		// its presence IS the registration as a retention template.
		return DispDeleteRetention, CatNone, nil
	}
	return "", CatNone, invalidf("unclassifiable statement kind %s", sh.Kind)
}

// bulkUpdateIsPerRowLWWSafe reports whether a bulk (non-full-PK) UPDATE can be applied by
// per-row LWW expansion: it must assign updated_at (the incoming clock each matched row is
// gated by). A rekey of a primary-key column is still safe — the expansion enumerates by the
// original predicate and applies each row scoped to its FULL prior PK, so it becomes a
// row-scoped rekey that simply back-pressures (fails closed) if the new key collides with an
// existing row.
func bulkUpdateIsPerRowLWWSafe(sh StmtShape) bool {
	return sh.UpdatedAtParamIdx >= 0
}

// explicitPolicyDef is an audited, hand-maintained disposition for a specific statement whose
// safe handling can NOT be auto-derived — currently the no-clock full-PK updates. Each names
// its exact statement and, for a monotonic-timestamp update, the column the receiver must only
// ADVANCE (never regress on an out-of-order write). Idempotent/terminal updates leave
// MonotoneColumn empty and apply verbatim.
type explicitPolicyDef struct {
	SQL            string
	Disposition    Disposition
	MonotoneColumn string
	// RequiresCapability/DispositionAfter make a shape CAPABILITY-GATED (Part H): before the
	// capability is active on the receiver, Disposition applies (use DispReject to fail closed);
	// once active, DispositionAfter applies. Empty ⇒ an ungated policy.
	RequiresCapability string
	DispositionAfter   Disposition
}

var explicitPolicyDefs = []explicitPolicyDef{
	// audit_log hash-chain reseal: idempotent (recomputes the same hashes) → verbatim.
	{SQL: `UPDATE audit_log SET prev_hash = ?, content_hash = ? WHERE id = ?`, Disposition: DispFullPKUpdateNoClock},
	// session revoke: a guarded one-shot terminal transition (WHERE revoked_at IS NULL) → verbatim.
	{SQL: `UPDATE sessions SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL`, Disposition: DispFullPKUpdateNoClock},
	// session touch: last_used_at must only advance (align with AE's timestamp-max merge).
	{SQL: `UPDATE sessions SET last_used_at = ? WHERE id = ? AND revoked_at IS NULL`, Disposition: DispFullPKUpdateNoClock, MonotoneColumn: "last_used_at"},
	// token touch: last_used_at must only advance.
	{SQL: `UPDATE tokens SET last_used_at = ? WHERE id = ?`, Disposition: DispFullPKUpdateNoClock, MonotoneColumn: "last_used_at"},
	// Canonical registry-credential upsert (Part H2): REJECT until canonical_registry_v1 is active
	// on this receiver (so a prematurely-enabled peer can't inject canonical rows while legacy
	// writers still run), then apply through DispCanonicalRegistry, which verifies the
	// deterministic-ID contract before the LWW upsert.
	{SQL: registryCanonicalUpsertSQL, Disposition: DispReject, RequiresCapability: capCanonicalRegistryV1, DispositionAfter: DispCanonicalRegistry},
	// Legacy mint-new-id registry INSERT (Part H2, point 7): apply normally UNTIL the canonical
	// writer is on cluster-wide (canonical_registry_active_v1 latched), then REJECT — a stray legacy
	// INSERT after activation (a bug / an old or pre-barrier returning node) would create a
	// duplicate physical row for a triple that already has its canonical row.
	{SQL: registryLegacyInsertSQL, Disposition: DispPlainInsert, RequiresCapability: capCanonicalRegistryActiveV1, DispositionAfter: DispReject},
}

var explicitPolicyByFP = buildExplicitPolicies()

func buildExplicitPolicies() map[string]LedgerEntry {
	m := make(map[string]LedgerEntry, len(explicitPolicyDefs))
	for _, d := range explicitPolicyDefs {
		fp, err := FingerprintSQL(d.SQL)
		if err != nil {
			panic("explicit policy SQL does not parse: " + d.SQL + ": " + err.Error())
		}
		m[fp] = LedgerEntry{
			Disposition:        d.Disposition,
			MonotoneColumn:     d.MonotoneColumn,
			RequiresCapability: d.RequiresCapability,
			DispositionAfter:   d.DispositionAfter,
		}
	}
	return m
}

// explicitPolicy returns the audited per-fingerprint policy, if one is registered.
func explicitPolicy(fp string) (LedgerEntry, bool) {
	e, ok := explicitPolicyByFP[fp]
	return e, ok
}

// LedgerEntryFor derives the compatibility-ledger entry for one replicated builder statement.
// The CI guard's -emit-ledger mode calls it to generate stmtledger_generated.go. An explicit,
// audited per-fingerprint policy (explicitPolicyDefs) overrides derivation.
func LedgerEntryFor(sql string) (LedgerEntry, error) {
	table := extractTableName(sql)
	pkCols := tablePrimaryKeys[table]
	sh, err := parseStmtShape(sql, pkCols)
	if err != nil {
		return LedgerEntry{}, err
	}
	fp := stmtFingerprint(sh)
	if e, ok := explicitPolicy(fp); ok {
		e.Fingerprint, e.Kind, e.Table = fp, sh.Kind.String(), sh.Table
		return e, nil
	}
	disp, cat, err := deriveDisposition(sh)
	if err != nil {
		return LedgerEntry{}, err
	}
	return LedgerEntry{Fingerprint: fp, Kind: sh.Kind.String(), Table: sh.Table, Disposition: disp, Category: cat}, nil
}
