package corrosion

import "strings"

// appendOnlyTables are immutable append-only tables: a replicated INSERT is applied with
// INSERT OR IGNORE and never LWW-gated, because a row never changes after creation.
var appendOnlyTables = map[string]bool{
	"fencing_log":  true,
	"audit_log":    true,
	"mutation_log": true,
	"vm_events":    true,
}

// deriveDisposition classifies a parsed replicated statement into the disposition the apply
// path uses. It is the single source of truth for authorization: the compatibility ledger
// (stmtledger_generated.go) is generated by running it over every builder statement, so a
// fingerprint's ledger disposition and its derivation can never disagree. A statement it
// can't classify safely returns an error, which fails the CI guard (the shape must be made
// classifiable before it can ship).
func deriveDisposition(sh StmtShape) (Disposition, ConcurrencyCategory, error) {
	t := sh.Table
	// Custom-merge tables (monotone lifecycle / immutable journal) merge by their own rule
	// regardless of statement kind.
	if customMergeTables[t] != nil {
		return DispCustomMerge, CatNone, nil
	}
	switch sh.Kind {
	case KindInsert:
		// append-only applies to INSERTs: never overwrite an existing immutable row.
		if appendOnlyTables[t] {
			return DispAppendOnly, CatNone, nil
		}
		if sh.OnConflict != nil {
			return DispExplicitUpsert, CatNone, nil
		}
		return DispPlainInsert, CatNone, nil
	case KindUpdate:
		// A full-PK UPDATE is LWW-gated + applied verbatim (guards retained). This also
		// covers deterministic full-PK fixups on otherwise append-only tables (e.g. the
		// audit_log hash-chain reseal): idempotent and keyed by PK.
		if sh.HasFullPKIdentity {
			return DispFullPKUpdate, CatNone, nil
		}
		// A bulk UPDATE (no full-PK identity) is applied by per-row LWW expansion — but only
		// when that is provably safe: it must advance a clock (SET updated_at = ?) so each
		// matched row can be LWW-gated, and it must NOT modify a primary-key column (rekeying
		// a PK can't be gated by that PK; those cascades are row-scoped at the source). Any
		// other bulk shape is unsupported and back-pressures.
		if bulkUpdateIsPerRowLWWSafe(sh) {
			return DispBulkUpdate, CatPerRowLWW, nil
		}
		return DispBulkUpdate, CatUnsupported, nil
	case KindDelete:
		// A DELETE reaches the ledger only when emitted by a known replicating builder, so
		// its presence IS the registration as a retention template.
		return DispDeleteRetention, CatNone, nil
	}
	return "", CatNone, invalidf("unclassifiable statement kind %s", sh.Kind)
}

// bulkUpdateIsPerRowLWWSafe reports whether a bulk (non-full-PK) UPDATE can be applied by
// per-row LWW expansion: it must assign updated_at (the incoming clock each row is gated by)
// and must not assign any primary-key column (a PK rekey can't be gated by that PK).
func bulkUpdateIsPerRowLWWSafe(sh StmtShape) bool {
	if sh.UpdatedAtParamIdx < 0 {
		return false // no bound incoming clock ⇒ can't LWW-gate the expansion
	}
	pkSet := lowerStringSet(tablePrimaryKeys[sh.Table])
	for _, a := range sh.SetAssigns {
		if pkSet[strings.ToLower(a.Column)] {
			return false // modifies a PK column ⇒ identity rekey, not per-row-LWW-safe
		}
	}
	return true
}

// LedgerEntryFor derives the compatibility-ledger entry for one replicated builder statement.
// The CI guard's -emit-ledger mode calls it to generate stmtledger_generated.go.
func LedgerEntryFor(sql string) (LedgerEntry, error) {
	table := extractTableName(sql)
	pkCols := tablePrimaryKeys[table]
	sh, err := parseStmtShape(sql, pkCols)
	if err != nil {
		return LedgerEntry{}, err
	}
	disp, cat, err := deriveDisposition(sh)
	if err != nil {
		return LedgerEntry{}, err
	}
	return LedgerEntry{
		Fingerprint: stmtFingerprint(sh),
		Kind:        sh.Kind.String(),
		Table:       sh.Table,
		Disposition: disp,
		Category:    cat,
	}, nil
}
